### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by Voyga** [davidlazar/vuvuzela#15]
```bash
$ go get github.com/davidlazar/vuvuzela/...

package golang.org/x/crypto/salsa20: unrecognized import path "golang.org/x/crypto/salsa20"
package golang.org/x/crypto/nacl/box: unrecognized import path "golang.org/x/crypto/nacl/box"
```

**Comment by schulze** [comment]
Are you on a system that block http requests or needs a proxy? The `go` tool needs to make http[s] requests in order to resolve the `golang.org/...` address, to the address of the actual Git repository.

**Comment by davidlazar** [comment]
What version of Go are you using?
`$ go version`

**Comment by Voyga** [comment]
@davidlazar 

```bash
$ go version
go version go1.5.3 darwin/amd64
```

Could it be an internet (proxy) issue? I'm in China.

**Comment by davidlazar** [comment]
It sounds like a proxy issue. To confirm, try running `go get` with the `-v` flag:

    $ go get -v github.com/davidlazar/vuvuzela/...
