### ISSUE TITLE
So how does this compare with WASTE?

### ISSUE THREAD

**Issue by kamilion** [davidlazar/vuvuzela#20]
Having been around the web for a while, I'm familiar with Justin Frankel's last stand at Nullsoft, WASTE.
https://en.wikipedia.org/wiki/WASTE

It keeps resurfacing over and over...
http://wasteagain.sourceforge.net/

What's different this time?

**Comment by davidlazar** [comment]
Vuvuzela is carefully designed to minimize metadata and uses differential privacy techniques to provably hide which users are communicating.  Our [SOSP 2015 paper](https://davidlazar.org/papers/vuvuzela.pdf) has more information.
